# Startup.R
# Set up environment for R analysis routines

#RELEASE
#BEGINCOPYRIGHT
###############
# R Source Code to accompany the manuscript
#
# "Comprehensive Maps of Drosophila Higher Olfactory Centers: 
# Spatially Segregated Fruit and Pheromone Representation"
# Cell (2007), doi:10.1016/j.cell.2007.01.040
# by Gregory S.X.E. Jefferis*, Christopher J. Potter*
# Alexander M. Chan, Elizabeth C. Marin
# Torsten Rohlfing, Calvin R. Maurer, Jr., and Liqun Luo
#
# Copyright (C) 2007 Gregory Jefferis <gsxej2@cam.ac.uk>
# 
# See flybrain.stanford.edu for further details
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#################
#ENDMAINCOPYRIGHT

# save location of current directory
owd=getwd()
# Identify location of startup script ...
if(interactive()){
	CodeDir<-dirname(attr(body(function() {}),'srcfile')$filename)
} else {
	if(exists("RootDir")){
		# somebody has already defined a variable called RootDir, which is assumed to be the root dir of AnalysisSuite
		CodeDir<-file.path(RootDir,"R","Code")
	} else {
		# guess!
		CodeDir=path.expand("~/projects/AnalysisSuite/R/Code")
	}
	if(!file.exists(CodeDir)){
		stop("Unable to locate AnalysisSuite. I was looking in: ",CodeDir,
		". You must either\n",
		" 1) Put AnalysisSuite there/symlink it\n",
		" 2) Or run R in --interactive mode\n",
		" 3) Define a variable called RootDir in your R session that points to the AnalysisSute directory\n",
		" 4) Or hard code location in your copy of AnalysisSuite!\n")
	}
}

# and use this to set other key locations
HomeDir<-dirname(CodeDir)
RootDir<-dirname(HomeDir)

# set to FALSE if you get bored of the copyright notice
if(interactive()) cat("Starting up Analysis Suite accompanying the paper
	\"Comprehensive Maps of Drosophila Higher Olfactory Centers: 
	Spatially Segregated Fruit and Pheromone Representation\"
	Cell (2007), doi:10.1016/j.cell.2007.01.040
	Gregory S.X.E. Jefferis*, Christopher J. Potter*, Alexander M. Chan, Elizabeth C. Marin
	Torsten Rohlfing, Calvin R. Maurer, Jr., and Liqun Luo
	
Code copyright (C) 2007 Gregory Jefferis <gsxej2@cam.ac.uk>
	 
See flybrain.stanford.edu for further details
	
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License\n\n")
# nice to name this computer - override if you wish
HostName=try(system("hostname",intern=TRUE, ignore.stderr=TRUE))

# Set up paths to other important directories
TestDir<-file.path(HomeDir,"Tests")

# This directory contains the 'object' files created by R
# after neurons have been read in from the data files generated by 
# Neurolucida.
ObjDir<-file.path(HomeDir,"Data")
setwd(ObjDir)

ScriptDir<-file.path(HomeDir,"ScriptDir")
# contains perl utility scripts (and perhaps registration binaries)
BinDir=file.path(RootDir,"bin")

AllRegDir=file.path(RootDir,"regfiles")
if(!file.exists(AllRegDir)){
	cat("Can't find the registration files for the Jefferis, Potter et al data set in directory:\n\t",
		AllRegDir,"\nPlease download and unzip regfiles.zip if you want to use the warping transformation tools from R","\n\n")
}

NotesDir=file.path(RootDir,"Notes")
ExamplesDir=file.path(HomeDir,"examples")
FigDir=file.path(HomeDir,"fig")
FigOutDir=file.path(HomeDir,"figout")

sourcelist<-list.files(path=CodeDir,patt="\\.[sR]$",recursive=TRUE)
sourcelist<-setdiff(sourcelist,"Startup.R")
SourcePaths<-file.path(CodeDir,sourcelist)
for (MyPath in SourcePaths) {
	#cat(MyPath," ")
	try(sys.source(MyPath,envir=topenv(),keep.source=TRUE))
}
# Define a numeric version for AnalysisSuite - we'll keep this in sync with 
# nat and insist that nat version is at least equal to AS major minor patch
ASVersion<-package_version('1.4.3')
natVersion=package_version(installed.packages()['nat','Version'])
if(!require("nat")){
  if(interactive())
    browseURL('https://github.com/jefferis/nat#installation')
  
  message("Please install nat R package\nSee https://github.com/jefferis/nat#installation")
  stop()
}
if(natVersion[1,1:3]<ASVersion[1,1:3]){
  if(interactive())
    browseURL('https://github.com/jefferis/nat#installation')
  message('***********')
  message('nat package version: ', natVersion,' is behind AnalysisSuite version: ',ASVersion)
  message("Please update nat R package\nSee https://github.com/jefferis/nat#installation")
  message('***********')
  stop()
}
# warn if nat major,minor is grater than AS
if(natVersion[1,1:2]>ASVersion[1,1:2]){
  message("nat version: ",natVersion,
          ' is >= one point ahead of AnalysisSuite version: ',ASVersion)
  message("You probably need to update AnalysisSuite!")
}

setwd(owd)
cat("Type: load(\"",file.path(ObjDir,'MyNeurons.rda'),"\")  to load in the main dataset\n",sep='')
#cat("Use runScript() or runFig() to run additional code\n")

# GJ 
# have not yet included a selection of Scripts and Figures for release
runScript<-function(d,dirpattern="ScriptDir$",IgnoreMissingDirs=TRUE){
	if(missing(d)){
		PossScriptDirNames<-ls(patt=dirpattern,envir=.GlobalEnv)
		if(length(PossScriptDirNames)==0) stop("Must supply a ScriptDir")
		# check if the dirs actually exist
		OriginalScriptDirNames<-PossScriptDirNames
		if(IgnoreMissingDirs){
			PossScriptDirs=sapply(PossScriptDirNames,get)
			dirExists=file.exists(PossScriptDirs)
			PossScriptDirNames=PossScriptDirNames[dirExists]
		}
		if(length(PossScriptDirNames)>1){
			d=select.list(PossScriptDirNames)
			d=get(d)
		} else if(length(PossScriptDirNames)==1) d=get(PossScriptDirNames)
		else stop("No readable fig dirs in candidates:",OriginalScriptDirNames)
	}
	if(file.exists(d)) sourceFiles=dir(d,patt="(R|s)$")
	else stop(paste("Directory",d,'not readable'))
	possFiles=file.path(d,select.list(sourceFiles))
	if(length(possFiles)==1){
		cat("source(",deparse(possFiles),")\n",sep="")
		invisible(source(possFiles))
	} 
	if(length(possFiles)>1) invisible(sapply(possFiles,source))
#	return(NULL)
}

runFig<-function(d,...){
	if(!missing(d)){
		runScript(d,...)
	} else runScript(dirpattern=".*FigDir$",...)
}

checkPackages<-function(required=NULL,suggested=NULL){
	allpackages=.packages(all = TRUE)
	missingreq=setdiff(required,allpackages)
	missingsug=setdiff(suggested,allpackages)
	if(length(missingreq)>0){
		missingreq=deparse(missingreq)
		stop(paste("Please install missing packages by running\n",sep="",
			"install.packages(",missingreq,")\n and then rerunning this script"))
	}
	if(length(missingsug)>0){
		missingsug=deparse(missingsug)
		warning(paste("You are missing some suggested packages.  You can install them by running\n",sep="",
			"install.packages(",missingsug,")\n and then rerunning this script"))
	}
}
